# Generated by Django 2.1.1 on 2018-09-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='try_count',
            field=models.IntegerField(default=1, verbose_name='Количество попыток'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='try_count',
            field=models.IntegerField(default=1, verbose_name='Количество попыток'),
        ),
    ]
