# Generated by Django 2.1.1 on 2018-09-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180906_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='try_count',
            field=models.IntegerField(default=0, verbose_name='Количество попыток'),
        ),
    ]
