# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token af002e05fa755512648bf8fb72bcb4547ae47211

{
  "title": "iWhatch",
  "description": "В исправном состоянии"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token af002e05fa755512648bf8fb72bcb4547ae47211

{
  "status": "CLOSED"
}

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token 2d8bae9bb48877555e5550f1de298e4c6329c2b9

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-03-06
Content-Type: application/json
