# Generated by Django 2.0.5 on 2019-03-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='название модели')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='цена')),
                ('image', models.CharField(max_length=255, verbose_name='URL изображения')),
                ('release_date', models.DateField(verbose_name='дата релиза')),
                ('lte_exists', models.BooleanField(verbose_name='имеется LTE')),
                ('slug', models.CharField(max_length=255, verbose_name='слагифицированное имя')),
            ],
        ),
    ]
