# Generated by Django 3.1.2 on 2020-10-17 10:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20201017_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
