# Generated by Django 3.1.2 on 2020-10-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(blank=True)),
                ('model', models.TextField(blank=True)),
                ('os', models.TextField(blank=True)),
                ('cam', models.TextField(blank=True)),
                ('color', models.TextField(blank=True)),
                ('ram', models.TextField(blank=True)),
                ('proc', models.TextField(blank=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt', models.TextField(blank=True, default='-')),
                ('wifi', models.TextField(blank=True, default='-')),
                ('sd', models.TextField(blank=True, default='-')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.phone')),
            ],
        ),
    ]
