# Generated by Django 2.0.5 on 2019-03-24 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(max_length=255, verbose_name='тип')),
                ('camera_matrix', models.PositiveIntegerField(verbose_name='матрица')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_os_family', models.CharField(max_length=255, verbose_name='семейство')),
                ('device_os_name', models.CharField(max_length=255, verbose_name='название системы')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=255, verbose_name='имя')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model', models.CharField(max_length=255, verbose_name='название модели')),
                ('phone_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='цена')),
                ('phone_memory', models.FloatField(verbose_name='размер оперативной памяти')),
                ('phone_ppi', models.PositiveIntegerField(blank=True, null=True, verbose_name='число пикселей на дюйм')),
                ('phone_fm_radio', models.BooleanField(verbose_name='FM-радио')),
                ('phone_addition', models.TextField(blank=True, max_length=4096, verbose_name='дополнительные параметры')),
                ('phone_cameras', models.ManyToManyField(to='phones.Camera', verbose_name='камера')),
                ('phone_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.Manufacturer', verbose_name='производитель')),
                ('phone_os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.DeviceOS', verbose_name='операционная система')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_model', models.CharField(max_length=255, verbose_name='название модели')),
                ('processor_frequency', models.PositiveIntegerField(blank=True, null=True, verbose_name='тактовая частота')),
                ('processor_cores', models.PositiveIntegerField(verbose_name='количество ядер')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeenResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical_screen_resolution', models.PositiveIntegerField(verbose_name='разрешение по-вертикали')),
                ('horisontal_screen_resolution', models.PositiveIntegerField(verbose_name='разрешение по-горизонтали')),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.Processor', verbose_name='процессор'),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_screen_resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phones.ScreeenResolution', verbose_name='разрешение экрана'),
        ),
    ]
