# Generated by Django 3.1.2 on 2020-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20201018_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqphone',
            name='bt',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='uniqphone',
            name='sd',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='uniqphone',
            name='wifi',
            field=models.TextField(default='-'),
        ),
    ]
