# Generated by Django 3.1.2 on 2020-10-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20201018_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqphone',
            name='bt',
            field=models.TextField(default='-'),
        ),
    ]
