# Generated by Django 3.1.2 on 2020-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128)),
                ('is_main', models.NullBooleanField()),
                ('scopes', models.ManyToManyField(related_name='namescope', to='articles.Article')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
