# Generated by Django 3.1.2 on 2020-10-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlescope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={},
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='scopes',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(null=True, verbose_name='Основной'),
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='name',
        ),
        migrations.AddField(
            model_name='articlescope',
            name='name',
            field=models.ManyToManyField(max_length=128, related_name='scopes', to='articles.Article', verbose_name='Название раздела'),
        ),
    ]
