# Generated by Django 3.1.2 on 2020-10-22 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201022_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(related_name='scopes', to='articles.ArticleScope', verbose_name='Тематика раздела'),
        ),
        migrations.AddField(
            model_name='articlescope',
            name='delete',
            field=models.BooleanField(null=True, verbose_name='Удалить'),
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='name',
        ),
        migrations.AddField(
            model_name='articlescope',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, max_length=128, verbose_name='Название раздела'),
            preserve_default=False,
        ),
    ]
