# Generated by Django 3.1.2 on 2020-10-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20201022_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='is_main',
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(null=True, verbose_name='Основной')),
                ('delete', models.BooleanField(null=True, verbose_name='Удалить')),
                ('article_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.article')),
                ('scope_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.articlescope')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='name_scope',
            field=models.ManyToManyField(related_name='scopes', through='articles.Scope', to='articles.ArticleScope', verbose_name='Тематика раздела'),
        ),
    ]
