# Generated by Django 3.1.2 on 2020-10-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201022_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='scope_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articlescope'),
        ),
    ]
