# Generated by Django 3.1.2 on 2020-10-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201023_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name_scope',
            field=models.ManyToManyField(related_name='Тематика_Раздела', through='articles.Scope', to='articles.ArticleScope', verbose_name='Тематика раздела'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='scope_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scp_name', to='articles.articlescope', verbose_name='Название'),
        ),
    ]
