# Generated by Django 3.1.2 on 2020-10-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20201024_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescope',
            name='is_main',
        ),
        migrations.AddField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
