# Generated by Django 3.1.2 on 2020-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20201024_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name_scope',
            field=models.ManyToManyField(related_name='scopes', through='articles.Scope', to='articles.ArticleScope', verbose_name='Тематика раздела'),
        ),
    ]
