# Generated by Django 3.1.2 on 2020-10-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20201026_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_name', to='articles.article', verbose_name='Тематика'),
        ),
    ]
