# Generated by Django 3.1.2 on 2020-10-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20201026_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='art_name', to='articles.article', verbose_name='Тематика'),
        ),
    ]
