# Generated by Django 3.1.2 on 2020-10-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20201026_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_name', to='articles.article', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='scope_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scp_name', to='articles.articlescope', verbose_name='Название'),
        ),
    ]
