# Generated by Django 4.0.6 on 2022-08-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_teg_tegofarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teg',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='teg',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
