# Generated by Django 4.0.6 on 2022-08-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_teg_options_alter_teg_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.DeleteModel(
            name='TegOfArticle',
        ),
    ]
