# Generated by Django 4.0.6 on 2022-08-11 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_options_delete_tegofarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TegOfArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_teg', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.article')),
                ('teg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.teg')),
            ],
        ),
    ]
