# Generated by Django 4.0.6 on 2022-08-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_teg_options_alter_tegofarticle_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teg',
            name='articles',
            field=models.ManyToManyField(related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='tegofarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='tegofarticle',
            name='teg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='articles.teg'),
        ),
    ]
