# Generated by Django 4.0.6 on 2022-08-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_teg_articles_alter_tegofarticle_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teg',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='tegofarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='tegofarticle',
            name='teg',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Teg',
        ),
        migrations.DeleteModel(
            name='TegOfArticle',
        ),
    ]
