# Generated by Django 4.0.6 on 2022-08-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tegofarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='tegofarticle',
            name='teg',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.DeleteModel(
            name='Teg',
        ),
        migrations.DeleteModel(
            name='TegOfArticle',
        ),
    ]
