# Generated by Django 4.0.6 on 2022-08-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_teg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teg',
            name='main_teg',
        ),
    ]
