# Generated by Django 4.0.6 on 2022-08-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_teg_main_teg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teg',
            name='teg',
        ),
        migrations.CreateModel(
            name='ArticleTeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_teg', models.BooleanField(verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article')),
                ('teg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.teg')),
            ],
        ),
    ]
