# примеры API-запросов

# получение объявлений
GET 127.0.0.1:8000/api/advertisements/
Content-Type: application/json

###
# создание объявления
POST 127.0.0.1:8000/api/advertisements/
Content-Type: application/json
Authorization: Token fb30cef9fe8a12659a036bfb5e94c64cee16f094

{
  "title": "шкаф",
  "description": "зеро"
}

###

# попытка поменять объявление
PATCH 127.0.0.1:8000/api/advertisements/23/
Content-Type: application/json
Authorization: Token fb30cef9fe8a12659a036bfb5e94c64cee16f094

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET 127.0.0.1:8000/api/advertisements/?status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET 127.0.0.1:8000/api/advertisements/?created_at_before=2019-10-01
Content-Type: application/json

###
