# Generated by Django 4.1.2 on 2023-01-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacherstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
