# Generated by Django 4.1.2 on 2023-01-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_student_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.student'),
        ),
        migrations.AlterField(
            model_name='teacherstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.teacher'),
        ),
    ]
