# Generated by Django 3.1.2 on 2020-10-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20201028_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.project'),
        ),
    ]
