# Generated by Django 4.2.2 on 2023-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
