# Generated by Django 4.2.2 on 2023-06-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
