# Generated by Django 2.1.1 on 2018-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='No title', max_length=100),
            preserve_default=False,
        ),
    ]
