# Generated by Django 4.0.6 on 2022-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('image', models.ImageField(upload_to='')),
                ('releaze_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
    ]
