# Generated by Django 4.0.6 on 2022-08-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='releaze_date',
            new_name='release_date',
        ),
    ]
